Mark duplicate hotkeys
Eugeny/tabby pull request #7667
Opened 2022-12-18 20:10 UTC by BenjaminBrandmeier

Feature to mark duplicate hotkeys. Solves https://github.com/Eugeny/tabby/issues/2704.

![hotkey_duplicates](https://user-images.githubusercontent.com/17959794/208317092-db293f01-2d9b-4937-af18-ddc3c152e4d8.gif)

2022-12-18 20:19 UTC, Eugeny requested changes
Otherwise LGTM 👍

2022-12-18 20:19 UTC, Eugeny commented on tabby-settings/src/components/hotkeySettingsTab.component.ts
> +            .filter(hotkey => JSON.stringify(hotkey) === JSON.stringify(strokes))
I'd prefer `deepEquals` here since JSON won't guarantee key order if hotkeys would contain dicts some day.

2022-12-18 20:19 UTC, Eugeny commented on tabby-settings/src/components/multiHotkeyInput.component.ts
> +import { Hotkey } from 'tabby-core/src/api/hotkeyProvider'
`Hotkey` should be barrel-exported through `tabby-core/src/index.ts`, same as everything else

2022-12-19 00:07 UTC, merged

2022-12-19 00:07 UTC, Eugeny commented
Great work!

2023-01-06 15:45 UTC, Eugeny commented
Unfortunately it's now making filtering unusable - do you think you could make it faster than O(N^2)? E.g. stick all keystrokes into a Set and look up from it.

<img width="684" alt="Screenshot 2023-01-06 at 16 44 41" src="https://user-images.githubusercontent.com/161476/211046589-a054aa55-469e-47df-894e-153c41d8669a.png">

2023-01-06 19:15 UTC, BenjaminBrandmeier commented
Absolutely! Will create a performance fix PR within the next minutes.