Fix Issue #4946 Basic folder upload for sftp electron.
Eugeny/tabby pull request #9891
Opened 2024-08-21 05:56 UTC by marko1616

# 🚀 Basic Folder Upload Feature for SFTP in Electron

> **⚠️ DO NOT MERGE FOR NOW**  
> **Status:** _Under Review_

## 📝 Description

I have implemented a **folder upload feature** for the SFTP functionality within Electron. This enhancement allows users to upload entire folders, which could significantly improve the user experience for bulk file transfers.

### Key Features:
- 📁 **Folder Upload**: Supports uploading entire directories, not just individual files.
- ⚙️ **Electron Integration**: Seamlessly integrated with the existing Electron framework.
- 🔄 **Basic Error Handling**: Initial handling of common upload errors (e.g., connection issues).

## 🤔 Concerns

I'm uncertain if this is the most effective or maintainable approach for implementing folder uploads. There may be more optimized methods to achieve this functionality. **Your feedback is crucial** in determining the best path forward.

## 🙏 Acknowledgments

I would like to express my sincere gratitude to all the project developers for their continued efforts and invaluable contributions. Your hard work has laid the foundation for features like this to be developed.

## 🚧 Next Steps

If the team agrees that this is a suitable implementation:
1. 🔍 **Refinement**: I will incorporate your feedback and make necessary adjustments.
2. 🧪 **Testing**: Further testing and validation will be conducted to ensure robustness.
3. ✅ **Completion**: Final touches and documentation updates.

Thank you for taking the time to review this PR. Your insights and suggestions will be highly appreciated!

2024-08-21 07:55 UTC, Eugeny requested changes
Just a few comments, looks good otherwise!

Also, `startUploadFromDragEvent` would need to also support folder drop events too

2024-08-21 07:55 UTC, Eugeny commented on tabby-ssh/src/components/sftpPanel.component.ts
> +                    this.sftp.mkdir(path.join(this.path, accumPath)).then(() => {
Needs an await here

2024-08-21 07:55 UTC, Eugeny commented on tabby-ssh/src/components/sftpPanel.component.pug
> +        div(translate) Upload Folder
```suggestion
        div(translate) Upload folder
```

2024-08-21 07:55 UTC, Eugeny commented on tabby-ssh/src/components/sftpPanel.component.pug
>          div(translate) Upload
```suggestion
        div(translate) Upload files
```

2024-08-21 07:55 UTC, Eugeny commented on tabby-ssh/src/components/sftpPanel.component.ts
> +                for (const pathParts of path.posix.dirname(transfer.getRelativePath()).split(path.posix.sep)) {
Will this still work on Windows (`path.posix`)?

2024-08-21 07:55 UTC, Eugeny commented on tabby-core/src/api/platform.ts
> +    getRelativePath (): string {
should return `string|null` instead of an empty string for clarity

2024-08-21 07:55 UTC, Eugeny commented on tabby-electron/src/services/platform.service.ts
> +            let allFiles: string[] = []
An array of `{ fullPath: string, relativePath: string }` would be cleaner than two separate `string[]`s

2024-08-21 07:55 UTC, Eugeny commented on tabby-ssh/src/components/sftpPanel.component.ts
> +                        this.notifications.notice('The directory was created successfully')
No need for a notification here

2024-08-21 21:46 UTC, marko1616 commented
What do you think about making a directory an ElectronFileUpload object? This way, we can treat a directory as a file, ensuring that even empty directories can be uploaded.

2024-08-22 00:14 UTC, marko1616 commented on tabby-ssh/src/components/sftpPanel.component.ts
> +                for (const pathParts of path.posix.dirname(transfer.getRelativePath()).split(path.posix.sep)) {
Windows (at least Windows 10 and above) supports the POSIX standard for SFTP file uploads(I've tested it), but Linux (and other similar systems) do not support Windows' path format. If the code here doesn't use `path.posix` and you upload files from a Windows system to a Linux server, it will result in a chaotic path like `/home/sb\path\to\something`.

2024-08-22 14:57 UTC, Eugeny commented
If you'd like to implement empty folder "uploading", I suggest two ways:
a) have `startUploads[FromDragEvent]` return `(FileUpload|EmptyDirectory)[]` where `EmptyDirectory` is `{ relativePath: string }`
b) implement `DirectoryUpload` that would specify its children explicitly, this way you can also avoid the need for `relativePath` altogether

2024-08-23 03:46 UTC, marko1616 commented
Oaky I'v done all the feats.

2024-08-24 13:18 UTC, marko1616 commented
cc @Eugeny you can now at a final check for this pr.Thx

2024-08-24 21:49 UTC, Eugeny commented
Looking good now, thanks!

@all-contributors please add @marko1616 for code

2024-08-24 21:49 UTC, merged